### ISSUE TITLE
Initialize PDS-ESDIS NGAP Pilot Project

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/cloud-tasks#10]
Sub-tasks TBD, but planning on testing out using ESDIS' NGAP to create a "PDS Cloud" in AWS.

**Comment by jordanpadams** [comment]
📆 December status: Awaiting contact from ESDIS. Will follow-up in the next couple weeks. Pilot task is outside of B12.1 deliverables

**Comment by jordanpadams** [comment]
📆 January status: Start delayed. awaiting contact from ESDIS. beta dev task so no impact on B12.1

**Comment by tloubrieu-jpl** [comment]
@jimmie can you create subtask for this EPIC and assign one to this sprint, to get the collaboration with NGAP going. I guess the first ticket will be the creation of the users.

**Comment by jordanpadams** [comment]
📆 February status: initial kick-off meeting planned for 3/2.

**Comment by jordanpadams** [comment]
this is done for B13.0 tasks. initial onboarding info documented here: https://wiki.jpl.nasa.gov/display/PDSEN/NGAP+Cloud
