### ISSUE TITLE
Deploy production registries

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/cloud-tasks#12]

**Comment by tloubrieu-jpl** [comment]
The geo elasticsearch database snapshot can not be retrieved by Jimmie for now (500 error). See DSiO-1151.

**Comment by tloubrieu-jpl** [comment]
The 500 error had been solved by working on the user roles, so the GEO elasticsearch work.

**Comment by tloubrieu-jpl** [comment]
@jimmie is sending email notifications to the node.

He's also preparing a short documentation to describe the deployment to the nodes (on pds-registry-app repository site)

**Comment by jordanpadams** [comment]
completed. documentation to come per https://github.com/NASA-PDS/pds-registry-app/issues/240
