### ISSUE TITLE
Registry ES version incompatible with available available AWS managed ES / OpenSearch versions

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/cloud-tasks#13]

**Comment by jimmie** [comment]
Eugene mentioned that he tests w/ ES version 7.10 and API 7.15.1. Next steps will be to deploy the test/staging registry with these versions and verify all is working. Assuming this works, we will upgrade the ES versions of EN, GEO and IMG, upgrade the service to the latest. New registry deployments will then use the same versions.

**Comment by jimmie** [comment]
Unfortunately, the build flavor of the AWS ES (i.e. 'css') is different from the Docker ES image ('default') - the latter value required by the >=7.14 versions of the High Level API. See [issue #97](https://github.com/NASA-PDS/registry-api-service/issues/97) which describes the solution we will pursue for now.

**Comment by jimmie** [comment]
this has been addressed via [issue #6](https://github.com/NASA-PDS/registry-api/issues/6)
