### ISSUE TITLE
Implement CCS across node registries

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/cloud-tasks#14]
## 💡 Description

Work with SAs to implement CCS across all DN registries

**Comment by tloubrieu-jpl** [comment]
This works and is deployed.

**Comment by tloubrieu-jpl** [comment]
This was done manually by the SAs (dev team or Jimmie are not allowed to do it)

**Comment by jimmie** [comment]
Closing for now - we should revisit (testing) once more nodes have consumed data
