### ISSUE TITLE
Update Node Registries to allow public read / query

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/cloud-tasks#19]
## 💡 Description

Currently, they are only allowed from whitelisted subnets. This needs to be updated for querying the APIs.

**Comment by jordanpadams** [comment]
To enable this, per @jimmie we need to 2 hostnames: 1 for cloudfront and 1 for load balancer

cloudfront - both pds.nasa.gov and pds.jpl.nasa.gov
load balancer - ? - per discussions, most likely option pds-gamma-engineering.jpl.nasa.gov

**Comment by viviant100** [comment]
@jimmie I cannot view [DSIO-1387](https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-1387).  Could you add me to the ticket?  Thanks.

**Comment by jimmie** [comment]
API access has been enabled through pds.nasa.gov and jpl.pds.nasa.gov - PR#23 above has been merged.
