### ISSUE TITLE
Setup AWS Access from pds-rpt for web statistics

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/cloud-tasks#20]
## 💡 Description

To support web analytics task to push logs from pds-rpt using logstash

**Comment by tloubrieu-jpl** [comment]
Not opensearch is going to be used but Athena or Spark

**Comment by tloubrieu-jpl** [comment]
Question from @viviant100 and @c-suh for @jordanpadams and @jimmie  , will that replace the current web analysis report that @c-suh runs ?

Do we still need to make the current web report work with the logs from the AWS deployment (lift-and-shift) of the PDS web site ?

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @c-suh @viviant100 @ yes. I believe we pull the logs from our current website using SCP (i.e. ssh). If that is the case, I think all we need to do is once we cutover is SSH manually into the new PDS.nasa.gov host to replace the SSH key and we should be good to go.

That being said, this task has nothing to do with the existing report service. That needs to go on for foreseeable future. This task is to enable pushing/pulling of logs from pds-rpt to an AWS service in order to play around with developing some web analytics for the PDS website unification work. Hopefully the tools @cgimber @kaipak come up with will replace the old report service eventually, but tbd.

**Comment by tloubrieu-jpl** [comment]
Thanks @jordanpadams , that is clearer to me now.

**Comment by kaipak** [comment]
++ @philipsoutham

**Comment by jimmie** [comment]
@philipsoutham, @kaipak : Susan asked if for now it would be sufficient to provide you access to the appropriate PDS S3 buckets so you can do the development on your own AWS account then export whatever is necessary to the PDS account once that is completed? If not, I will need the shopping list of items to be created on the PDS account.

**Comment by jordanpadams** [comment]
closing this for now. @philipsoutham is setting something up in a sandbox environment that we will move over to the PDS account after it has been setup
