### ISSUE TITLE
create users for NGAP

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/cloud-tasks#22]

**Comment by jimmie** [comment]
I have sent an email message to jason.werpy@nasa.gov and by request cc'd everyone at Thursday's (2/10) meeting including the initial list of people we want to establish as users in our NGAP sandbox: Jordan, Thomas, Vivian, Ramesh, Jimmie.

FYI: Jason wasn't included in the meeting invite, so I made my best guess as to his email address. It didn't bounce, so hopefully it's correct. If I don't hear back from him early next week (w.o. 2/14), I'll ping the distrib again to verify that he in fact received it.

I will close this ticket once I have confirmation that the users are created.

**Comment by jimmie** [comment]
Jason has scheduled a sandbox introduction meeting, unfortunately on an RDO. I have proposed some alternative times that appear to be suitable to most everyone's calendars.

**Comment by jordanpadams** [comment]
intro meeting done. onboarding documented here: https://wiki.jpl.nasa.gov/display/PDSEN/NGAP+Cloud
