### ISSUE TITLE
Work with Web Unification team to define system architecture for migration

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/cloud-tasks#30]
## 💡 Description

This ticket is about PDS EN being a 'manager/architect' for the AWS deployments of the discipline nodes.

**Comment by jordanpadams** [comment]
@kaipak how is this task going with the SAs?

**Comment by kaipak** [comment]
SA work is pretty much done. I should be done with migrating the data this coming week. I've gone through onboarding with data scientist on my team who will be helping out with the dashboards and we'll start on that next week as well.

**Comment by viviant100** [comment]
FYI, SA work can be found in DSIO-3371.

**Comment by jordanpadams** [comment]
@kaipak any way we can make sure we have this at least "mostly" migrated by next Thursday? the scripts don;t need to be completed yet. Just want to make sure the dashboards and the initial database are under the EN-managed cloud.

**Comment by kaipak** [comment]
Hey @jordanpadams, that is absolutely my goal. We had to work through some permissions errors between S3 and Athena but Rojeh seems to have resolved that.
