### ISSUE TITLE
Add logging to cloud front function

### ISSUE THREAD

**Issue by jimmie** [NASA-PDS/cloud-tasks#31]
It's pretty simple to add logging to the cloud front function which rewrites registry URIs, and would be greatly valuable for debugging issues.

Logging output goes to a CloudWatch log group w/ the function name.

**Comment by jordanpadams** [comment]
@jimmie is this still something that needs to be done? and what is the urgency for this would you say? is this something we should really have in place before any data or more services go online?

**Comment by jimmie** [comment]
This is not terribly urgent, just a nice to have to help diagnose request routing problems as they arise. There are other ways to accomplish this however.

**Comment by jordanpadams** [comment]
@jimmie can you chat with @viviant100 or post what you were thinking for this?

**Comment by jimmie** [comment]
Currently, the cloud front function doesn't output anything regarding requests received, errors in the requests, etc. This makes it a bit difficult to diagnose issues, although we haven't had any in a while. It would be good to hook up Cloudwatch logs by inserting various console.log() statements throughout.

More details here: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/edge-functions-logs.html

**Comment by jordanpadams** [comment]
thanks @jimmie! we will take a look

**Comment by jordanpadams** [comment]
@jimmie @viviant100 do we have any status on this?

**Comment by viviant100** [comment]
Did some research. We can start with hooking up CloudWatch with CloudFront.  @jimmie - Is this something we can do ourselves or need SA to setup?   On a separate note, are you using edge functions?

**Comment by jimmie** [comment]
PR [registry-api 264](https://github.com/NASA-PDS/registry-api/pull/264)
