### ISSUE TITLE
Make the current version of the API implementation (v1.0) be published under url 1.0 (instead of 0.4)

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/cloud-tasks#37]
## 💪 Motivation
In the future we will keep the version 1.0 of the API /api/search/1.0/ ... available, that will use minor upgrades of the registry-api, as long as the API specification is not significantly updated.

If a major version of the registry-api breaks the existing API specification, then we'll add a APi published under url /api/search/1.1 but will keep the existing url (1.0) for backward compatibility.

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by jordanpadams** [comment]
completed.
