### ISSUE TITLE
Jordan NGAP onboarding

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/cloud-tasks#44]
## 💡 Description

- [x] [DevOps Mindset: DevOps Principles & Implementation Approach (SKILLSOFT it_doexdodj_01_enus)](https://nasa-hcm03.ns2cloud.com/learning/user/common/viewItemDetails.do?componentTypeID=SKILLSOFT&componentID=it_doexdodj_01_enus&revisionDate=1293901200000&catalogCurrencyCode=USD&returnLink=%2Flearning%2Fuser%2Fcatalogsearch%2FcatalogSearchDispatchAction.do%3FsearchType%3DfilteredSearch%26keywords%3D&backto=%2Flearning%2Fuser%2Fcatalogsearch%2FcatalogSearchDispatchAction.do%3FsearchType%3DfilteredSearch%26keywords%3D)
- [x] [AWS Associate Solutions Architect 2020: AWS Developer Options](https://nasa-hcm03.ns2cloud.com/learning/user/common/viewItemDetails.do?componentTypeID=SKILLSOFT&componentID=it_clawsaa19_12_enus&revisionDate=1293901200000&catalogCurrencyCode=USD&returnLink=%2Flearning%2Fuser%2Fcatalogsearch%2FcatalogSearchDispatchAction.do%3FsearchType%3DfilteredSearch%26keywords%3D&backto=%2Flearning%2Fuser%2Fcatalogsearch%2FcatalogSearchDispatchAction.do%3FsearchType%3DfilteredSearch%26keywords%3D) (SKILLSOFT it_clawsaa19_12_enus)
- [x] [ELEVATED PRIVILEGES ON NASA INFORMATION SYSTEMS (COURSE ITS-002-09)](https://nasa-hcm03.ns2cloud.com/learning/user/common/viewItemDetails.do?componentTypeID=COURSE&componentID=ITS-002-09&revisionDate=1251475200000&catalogCurrencyCode=USD&returnLink=%2Flearning%2Fuser%2Fcatalogsearch%2FcatalogSearchDispatchAction.do%3FsearchType%3DfilteredSearch%26keywords%3D&backto=%2Flearning%2Fuser%2Fcatalogsearch%2FcatalogSearchDispatchAction.do%3FsearchType%3DfilteredSearch%26keywords%3D) (on NASA SATERN)

**Comment by jordanpadams** [comment]
Training complete. NAMS request submitted

**Comment by jordanpadams** [comment]
Done!
