### ISSUE TITLE
Develop timeline and plan for SBN-PSI migration

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/cloud-tasks#47]
## 💡 Description

As part of larger PDS Cloud migration plan

**Comment by jordanpadams** [comment]
Tabling until B13.1

**Comment by viviant100** [comment]
https://docs.google.com/presentation/d/1lN_WUwong4n6FkykQr4jAIRAVGaXxJh57aXkliXUf-8/edit#slide=id.g1f59d637613_7_75

**Comment by jordanpadams** [comment]
Done and presented to SBN-PSI
