### ISSUE TITLE
Configure opensearch to evenly distribute documents on nodes

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/cloud-tasks#54]
## 💡 Description

Following Dan Scholes issues with space on the GEO node, we noticed that the documents are all on one of the 3 nodes and the 2 others are empty.

Something need to be done with the shard configuration to distribute the documents evenly across the node.

Possibly the overall volume available could also be increased since Dan Scholes is expecting to load almost 90 milions documents and only 2 millions are loaded so far.

**Comment by jimmie** [comment]
All nodes' registry indexes have been re-indexed to utilize 3 shards. The exception is GEO which utilizes 6 w/ 300GB EBS.
