### ISSUE TITLE
Provide OpenSearch support to GEO

### ISSUE THREAD

**Issue by jimmie** [NASA-PDS/cloud-tasks#55]
Related to [cloud-tasks #54](https://github.com/NASA-PDS/cloud-tasks/issues/54) and includes [registry 132](https://github.com/NASA-PDS/registry/issues/132)- once the sharding strategy has been identified, increase GEO's overall space (add two more nodes) and provide Opensearch queries that identify the number of documents per mission.

**Comment by tloubrieu-jpl** [comment]
good progress on this ticket

**Comment by jimmie** [comment]
1.1.12 deployed, open search re-indexed.
