### ISSUE TITLE
Registry deployment for ESA-PSA

### ISSUE THREAD

**Issue by jimmie** [NASA-PDS/cloud-tasks#56]
Need a registry instance deployed for ESA-PSA.

**Comment by jimmie** [comment]
Everything is set up although waiting on a permissions fix for internal users to access Opensearch.

**Comment by tloubrieu-jpl** [comment]
The deployment should be done. Needs to be checked.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams @jimmie do you the status of the ESA-PDS deployment ?

The new entry should be listed there: 
https://nasa-pds.github.io/pds-api/guides/search/endpoints.html#endpoints
https://github.com/NASA-PDS/registry/wiki/Registry-Workshop-06_28_2022

The latter can be discussed as a better place might be found.

**Comment by tloubrieu-jpl** [comment]
And we also need to communicate with them (Mark ?) if this is ready.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl Jimmie and I are on an email thread with Mark back in November, but I do not see an email with the URL information. I just see an email where @jimmie was going to send him an LFT with his credentials. Will need more info from Jimmie when he is back.

**Comment by jimmie** [comment]
LFT messages sent, will wait for confirmation on their ability to access Opensearch and the registry.

**Comment by jimmie** [comment]
I am reopening to create a PR for the documentation update.

**Comment by jimmie** [comment]
pds-api #244 PR has been completed.
