### ISSUE TITLE
Initial investigation of TEA and how/if it can be adapted for the PDS

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/cloud-tasks#58]
## 💡 Description

Expected deliverable: some sort of write-up about what needs to be done for PDS to leverage TEA

**Comment by tloubrieu-jpl** [comment]
The application need to be deployed on NGAP to make accessible the bundle on S3 that Ramesh used for the Nucleus demo.

**Comment by jordanpadams** [comment]
Status: Scott got permissions to use EarthData login and test deployment. Reached out to Jason Werpy for additional assistance on Bastion proxy to access API endpoints

**Comment by jordanpadams** [comment]
Initial investigation completed. Demo completed at Sprint Review on 1/12

**Comment by collinss-jpl** [comment]
Charts detailing a rough understanding of the TEA workflows are available here: https://docs.google.com/presentation/d/1lbgsUFKEckQ0h263vG-Vixtzc6yqEnpI/edit?usp=share_link&ouid=106259062949823791797&rtpof=true&sd=true
