### ISSUE TITLE
Initial NGAP-to-MCP Migration Research

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/cloud-tasks#65]
## 💡 Description

* Research the components of NGAP we would want to have if we were to deploy PDS data and services in MCP.
* High-level scope of work and LOE to make it happen

- https://github.com/NASA-PDS/cloud-tasks/issues/68

**Comment by tloubrieu-jpl** [comment]
Meeting today with both NGAP and MCP, review of the services offered.

**Comment by jordanpadams** [comment]
📆 April Status: Kickoff meeting held with NGAP and MCP. Investigation has started with comparison. Scope increase has stretched the expected delivery date by 1 sprint.

**Comment by jordanpadams** [comment]
📆 May Status: Onboarding took significantly longer than expected. No impact on schedule anticipated as other tasks can be worked in parallel.

**Comment by jordanpadams** [comment]
📆 June status: Onboarding issues continuing causing 1 additional sprint delay. No impact on build.

**Comment by jordanpadams** [comment]
Wiki page and initial presentation created. This will continue to evolve over time, but we can call this good for this iteration. See internal wiki and search for "MCP and NGAP Comparison"
