### ISSUE TITLE
MCP Onboarding

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/cloud-tasks#68]
## 💡 Description

https://wiki.jpl.nasa.gov/pages/viewpage.action?pageId=771472177

- [x] @tloubrieu-jpl 
- [x] @ramesh-maddegoda 
- [x] @sjoshi-jpl 
- [x] @collinss-jpl
- [x] @nutjob4life 
- [x] @anilnatha
- [ ] ~@eddiesarevalo~
- [x] @c-suh 

@nutjob4life @tloubrieu-jpl @ramesh-maddegoda @sjoshi-jpl To get started, DevOps role is probably sufficient, but ultimately, I would like you 4 to have Systems Administration privileges, which requires a 4-hour training.

**Comment by nutjob4life** [comment]
Just started this process; for those following along, the "MCP Tenant Security" is over 12 pages long and you must affirm you've read it, along with the "MCP Tenant Rules of Behavior", which is thankfully just 1 page.

On the NAMS request instructions, "Is this a Request Role for Dev Ops, Admin, or Security Role" doesn't appear anywhere on the form, so I skipped it. For Tenant Organizational Unit, I selected "PDS". For Sponsor, I'm using @jordanpadams. 

For business justification?

> The Planetary Data System (PDS) continues to evolve into the cloud, ensuring that its many discipline-specific nodes have precise and continued access to scientific data. As a DevOps/Admin for the PDS, I require additional NASA account access for the Mission Cloud Platform (MCP). This ensures that development, innovation, maintenance, integrity, and availability of cloud-based PDS data discovery, analysis, and retrieval tools remains high.

How does that sound? I won't hit "submit" quite yet.

**Comment by nutjob4life** [comment]
I never read the manual 😆

**Comment by jordanpadams** [comment]
@nutjob4life 

> I'm not sure where to take the Sys Admin 4 hour training course.

NASA SATERN website

**Comment by nutjob4life** [comment]
Note from @ramesh-maddegoda: if you want to get the sys admin training, you'll need an IdMAX confidence rating of 50 or higher

**Comment by nutjob4life** [comment]
@ramesh … in progress, no indication yet on NAMS dashboard.

**Comment by nutjob4life** [comment]
@collinss-jpl has confirmed access to Kion dashboard.

**Comment by nutjob4life** [comment]
@sjoshi-jpl reports: has access but requires sysadmin role (has devops role). Will need training.

**Comment by nutjob4life** [comment]
@nutjob4life got access to Kion dashboard in about a day (devops role)

**Comment by nutjob4life** [comment]
@tloubrieu-jpl has made the NAMS request; perhaps will receive notification soon

**Comment by jordanpadams** [comment]
@anilnatha @eddiesarevalo @c-suh I know the training is annoying, but do we think we can get this completed by end of sprint? I think for the DevOps role, the training is pretty straightforward. Let me know if you encounter any additional roadblocks.

**Comment by c-suh** [comment]
@jordanpadams yes, I was scared off by mention of 4-hour training; thank you for clarifying that DevOps is not subject to that (or any training other than reading documents as far as I can tell)! I've submitted the NAMS request and am awaiting your approval.

**Comment by anilnatha** [comment]
I submitted the modification of my prior NAMS request to gain access to the PDS MCP account. I'll report back when I get a response.
