### ISSUE TITLE
AWS testing for PDS and PDS Engineering sites

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/cloud-tasks#9]
PDS
- [x] logins
- [x] user accounts
- [x] static content
- [ ] version control systems
- [ ] application configurations

PDS Engineering
- [x] logins
- [x] user accounts
- [x] static content
- [x] file uploads

**Comment by c-suh** [comment]
Applications are almost good. There is a new password for the RDS which needs to be updated on the following systems by @c-suh and @acyu :

- [ ] ds-status
- [ ] resource-manager
- [ ] subscription-service (coldfusion)
- [ ] other?

**Comment by tloubrieu-jpl** [comment]
Need to discuss the synchronization with pds-prodX, will be discussed in the next SA office hour.

Some backend components also remain to be migrated on AWS.

**Comment by c-suh** [comment]
- Synchronization has been discussed and the request submitted.
- Processes involving `/data` directory need to be (set up and) tested on AWS.
- Issues for a couple more applications are being looked at by @acyu.

**Comment by tloubrieu-jpl** [comment]
Some testing is going on before we can close this ticket

**Comment by c-suh** [comment]
@tloubrieu-jpl, I think this task has bled over into https://github.com/NASA-PDS/operations/issues/197. Should I list additional developments/tasks here (e.g. set up AWS gamma, set up sync) or close this ticket?

**Comment by tloubrieu-jpl** [comment]
This ticket is closed, the remaining work on the website will be done as part of  NASA-PDS/operations#197 or additional ticket if needed
